### ISSUE TITLE
The versions of some files in package downloaded from https://oss-cdn.nebula-graph.com.cn/third-party/nebula-third-party-src-5.0.tgz  specified by build.sh do not match those in xx.cmake in tag v3.4

### ISSUE THREAD

**Issue by xl-better** [vesoft-inc/nebula-third-party#124]
The versions of some files in package downloaded from https://oss-cdn.nebula-graph.com.cn/third-party/nebula-third-party-src-5.0.tgz  specified by build.sh do not match those in xx.cmake in tag v3.4, for example, boost.cmake, cachelib.cmake. And I can not access some of them. Should I obtain them from https://oss-cdn.nebula-graph.com.cn/third-party/nebula-third-party-src-3.0.tgz?

**Comment by Shinji-IkariG** [comment]
Yes, in fact 5.0-src.tgz corresponds to master, release-3.3 branch corresponds to 3.3-src.tgz, release-3.0 corresponds to 3.0-src.tgz

**Comment by xl-better** [comment]
I noticed that the latest release version is v3.4, is there any idea of making a 3.4-src.tgz package?

**Comment by Shinji-IkariG** [comment]
The release-3.3 branch is compatible with v3.4 tag/release. In fact, this release is derived from the nebula v3.4.0 release.
