### ISSUE TITLE
Build error, Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by cloud4us** [vesoft-inc/nebula-third-party#98]
**General Question**

I am trying to build nebula-third-party on Ubuntu 22.04 LTS. I have followed instructions from the readme. Here is the error I get:

nebula-third-party/build/build/build-info/autoconf-configure-.cmake:49 (message):
  Command failed: 1

   'env' 'CC=/usr/bin/cc' 'CXX=/usr/bin/c++' 'CFLAGS= -fcommon -fno-omit-frame-pointer -fPIC -O2 -D_DEFAULT_SOURCE -D_GNU_SOURCE -D_GLIBCXX_USE_CXX11_ABI=1' 'CXXFLAGS= -fcommon -fno-omit-frame-pointer -fPIC -O2 -D_DEFAULT_SOURCE -D_GNU_SOURCE -D_GLIBCXX_USE_CXX11_ABI=1' 'CPPFLAGS=-isystem /home/myuser/nebula-third-party/build/install/include -I/home/myuser/nebula-third-party/build/install/include/berkeleydb-5.1.29 -D_GLIBCXX_USE_CXX11_ABI=1' 'LDFLAGS=-L/home/***/nebula-third-party/build/install/lib -L/home/myuser/nebula-third-party/build/install/lib64 -L/home/myuser/nebula-third-party/build/install/lib/berkeleydb-5.1.29 -L/usr/lib/x86_64-linux-gnu  -static-libstdc++ -static-libgcc -pthread -ldl' 'PATH=/home/***/nebula-third-party/build/install/bin:/home/myuser/nebula-third-party/build/install/sbin:/home/myuser/nebula-third-party/build/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' 'ACLOCAL_PATH=/home/myuser/nebula-third-party/build/install/share/aclocal' 'LIBS=' './configure' '--prefix=/home/myuser/nebula-third-party/build/install'

  See also

    /home/myuser/nebula-third-party/build/build/build-info/autoconf-configure-*.log

make[2]: *** [CMakeFiles/autoconf.dir/build.make:93: build-info/autoconf-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:2678: CMakeFiles/autoconf.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

----
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

**Comment by wenhaocs** [comment]
Can you check the log `/home/myuser/nebula-third-party/build/build/build-info/autoconf-configure-*.log` to see detailed error msg?

**Comment by cloud4us** [comment]
@wenhaocs thanks for the quick reply! Here is the output:

cat /home/myuser/nebula-third-party/build/build.log
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Number of online physcial CPU cores: 2
-- Available physical memory: 15611 MB
-- Building third party with 2 jobs
-- Glibc version: 2.35
-- MIPS_LINK_FLAGS: 
-- Looking for C++ include elf.h
-- Looking for C++ include elf.h - found
-- breakpad: Use archived file
-- cachelib: Use archived file
-- use rocksdb native
-- libev: Use archived file
-- Configuring done
-- Generating done
-- Build files have been written to: /home/myuser/nebula-third-party/build/build
[  0%] Creating directories for 'berkeleydb'
[  0%] Performing download step (download, verify and extract) for 'berkeleydb'
-- verifying file...
       file='/home/myuser/nebula-third-party/build/tarballs/db-5.1.29.tar.gz'
-- File already exists and hash match (skip download):
  file='/home/myuser/nebula-third-party/build/tarballs/db-5.1.29.tar.gz'
  MD5='a94ea755ab695bc04f82b94d2e24a1ef'
-- extracting...
     src='/home/myuser/nebula-third-party/build/tarballs/db-5.1.29.tar.gz'
     dst='/home/myuser/nebula-third-party/build/build/berkeleydb/source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  0%] No update step for 'berkeleydb'
[  0%] No patch step for 'berkeleydb'
[  0%] Performing configure step for 'berkeleydb'
-- berkeleydb configure command succeeded.  See also /home/myuser/nebula-third-party/build/build/build-info/berkeleydb-configure-*.log
[  0%] Performing build step for 'berkeleydb'
-- berkeleydb build command succeeded.  See also /home/myuser/nebula-third-party/build/build/build-info/berkeleydb-build-*.log
[  0%] Performing install step for 'berkeleydb'
-- berkeleydb install command succeeded.  See also /home/myuser/nebula-third-party/build/build/build-info/berkeleydb-install-*.log
[  1%] Performing verify step for 'berkeleydb'
[  3%] Completed 'berkeleydb'
[  3%] Built target berkeleydb
[  3%] Creating directories for 'autoconf'
[  3%] Performing download step (download, verify and extract) for 'autoconf'
-- verifying file...
       file='/home/myuser/nebula-third-party/build/tarballs/autoconf-2.71.tar.gz'
-- File already exists and hash match (skip download):
  file='/home/myuser/nebula-third-party/build/tarballs/autoconf-2.71.tar.gz'
  MD5='f64e38d671fdec06077a41eb4d5ee476'
-- extracting...
     src='/home/myuser/nebula-third-party/build/tarballs/autoconf-2.71.tar.gz'
     dst='/home/myuser/nebula-third-party/build/build/autoconf/source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  4%] No update step for 'autoconf'
[  4%] No patch step for 'autoconf'
[  4%] Performing configure step for 'autoconf'
CMake Error at /home/myuser/nebula-third-party/build/build/build-info/autoconf-configure-.cmake:49 (message):
  Command failed: 1

   'env' 'CC=/usr/bin/cc' 'CXX=/usr/bin/c++' 'CFLAGS= -fcommon -fno-omit-frame-pointer -fPIC -O2 -D_DEFAULT_SOURCE -D_GNU_SOURCE -D_GLIBCXX_USE_CXX11_ABI=1' 'CXXFLAGS= -fcommon -fno-omit-frame-pointer -fPIC -O2 -D_DEFAULT_SOURCE -D_GNU_SOURCE -D_GLIBCXX_USE_CXX11_ABI=1' 'CPPFLAGS=-isystem /home/myuser/nebula-third-party/build/install/include -I/home/myuser/nebula-third-party/build/install/include/berkeleydb-5.1.29 -D_GLIBCXX_USE_CXX11_ABI=1' 'LDFLAGS=-L/home/myuser/nebula-third-party/build/install/lib -L/home/myuser/nebula-third-party/build/install/lib64 -L/home/myuser/nebula-third-party/build/install/lib/berkeleydb-5.1.29 -L/usr/lib/x86_64-linux-gnu  -static-libstdc++ -static-libgcc -pthread -ldl' 'PATH=/home/myuser/nebula-third-party/build/install/bin:/home/myuser/nebula-third-party/build/install/sbin:/home/myuser/nebula-third-party/build/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' 'ACLOCAL_PATH=/home/myuser/nebula-third-party/build/install/share/aclocal' 'LIBS=' './configure' '--prefix=/home/myuser/nebula-third-party/build/install'

  See also

    /home/myuser/nebula-third-party/build/build/build-info/autoconf-configure-*.log


make[2]: *** [CMakeFiles/autoconf.dir/build.make:93: build-info/autoconf-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:2678: CMakeFiles/autoconf.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by wenhaocs** [comment]
Can you show the errors in side: `/home/myuser/nebula-third-party/build/build/build-info/autoconf-configure-*.log
`

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
